CREATE OR REPLACE INTERNAL FUNCTION PUBLIC.find_in_set(str CHARACTER VARYING, str2 CHARACTER VARYING) 
 RETURNS BOOLEAN
 LANGUAGE SQL
AS $function$
 select $1 = ANY(STRING_TO_ARRAY($2, ',')) AS RESULT;
$function$;
