--用户表新增优缺点字段
ALTER TABLE KMJJW."sys_user" ADD ADVANTAGES varchar(1000) NULL;
ALTER TABLE KMJJW."sys_user" ADD DISADVANTAGES(1000) NULL;
--注释
COMMENT ON COLUMN KMJJW."sys_user"."ADVANTAGES" IS '优点';
COMMENT ON COLUMN KMJJW."sys_user"."DISADVANTAGES" IS '缺点';
