--职务
ALTER TABLE KMJJW."sys_user" ADD "USER_DUTY" VARCHAR(100) NULL;
--注释
COMMENT ON COLUMN KMJJW."sys_user"."USER_DUTY" IS '职务';
--职级
ALTER TABLE KMJJW."sys_user" ADD "USER_DUTY" VARCHAR(100) NULL;
--注释
COMMENT ON COLUMN KMJJW."sys_user"."USER_DUTY" IS '职级';
--职级
ALTER TABLE KMJJW."sys_user" ADD "DUTY_RANK_TYPE" VARCHAR(100) NULL;
--注释
COMMENT ON COLUMN KMJJW."sys_user"."DUTY_RANK_TYPE" IS '职务职级类型';
